version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - docker build -t analyze-user-data-function .
      - export IMAGE_TAG=$(date +%s | sha256sum | base64 | head -c 8)
      - echo $IMAGE_TAG
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 637423352927.dkr.ecr.us-east-2.amazonaws.com
      - docker tag analyze-user-data-function:latest 637423352927.dkr.ecr.us-east-2.amazonaws.com/analyze-user-data-function:$IMAGE_TAG
      - docker push 637423352927.dkr.ecr.us-east-2.amazonaws.com/analyze-user-data-function:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
  discard-paths: yes
